name: z=z^2+c | ${{ inputs.map_resolution }}x${{ inputs.map_resolution }} | ${{ inputs.max_iterations }} iterations | ${{ inputs.step }} step size

on:
  workflow_dispatch:
    inputs:
      map_resolution:
        description: "Image length/width (u64)"
        required: true
        default: 1000
      max_iterations:
        description: "Max iterations (u32)"
        required: true
        default: 10000
      step:
        description: "Step size for grid scan (f64)"
        required: true
        default: 0.005
      segments:
        description: "Number of segments (saves memory) (u64)"
        required: true
        default: 1

permissions:
  id-token: write
  contents: read

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build and Run
        run: |
          echo "Setting Rust constants from inputs..."
          sed -i 's/^const MAP_RESOLUTION: f64 = .*;/const MAP_RESOLUTION: f64 = ${{ inputs.map_resolution }} as f64;/' src/main.rs
          sed -i 's/^const MAX_ITERATIONS: u32 = .*;/const MAX_ITERATIONS: u32 = ${{ inputs.max_iterations }};/' src/main.rs
          sed -i 's/^const STEP: f64 = .*;/const STEP: f64 = ${{ inputs.step }};/' src/main.rs
          sed -i 's/^const SEGMENTS: u64 = .*;/const SEGMENTS: u64 = ${{ inputs.segments }};/' src/main.rs

          cargo build --release
          cargo run

      - name: Check For Output
        run: |
          if [ ! -f output.png ]; then
            echo "Error: output.png not found!"
            exit 1
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::679274284562:role/UploadMathArtRendering
          role-session-name: math-art-rendering-upload
          aws-region: us-east-1

      - name: Upload To S3
        run: |
          UUID=$(uuidgen)
          BUCKET_NAME="math-art-renderings"
          S3_PATH="s3://$BUCKET_NAME/$UUID.png"
          aws s3 cp output.png $S3_PATH
          echo "Rendering [available here.](https://$BUCKET_NAME.s3.us-east-1.amazonaws.com/$UUID.png)" >> $GITHUB_STEP_SUMMARY
