name: Generate Rendering

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build and Run
        run: |
          cargo build --release
          cargo run

      - name: Check For Output
        run: |
          if [ ! -f output.png ]; then
            echo "Error: output.png not found!"
            exit 1
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::679274284562:role/UploadMathArtRendering
          role-session-name: math-art-rendering-upload
          aws-region: us-east-1

      - name: Upload To S3
        run: |
          UUID=$(uuidgen)
          BUCKET_NAME="math-art-renderings"
          S3_PATH="s3://$BUCKET_NAME/$UUID.png"
          aws s3 cp output.png $S3_PATH
          echo "Rendering [available here.](https://$BUCKET_NAME.s3.us-east-1.amazonaws.com/$UUID.png)" >> $GITHUB_STEP_SUMMARY
